default:
  sessions:
    default:
      database: reaccting_test
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: reaccting_test
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

development:
  sessions:
    default:
      database: reaccting_development
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
  options:
    raise_not_found_error: false
